
OrdererOrgs:
  - Name: Orderer
    Domain: sample.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.sample.com
    Template:
      Count: 3
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.sample.com
    Template:
      Count: 3
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.sample.com
    Template:
      Count: 3
    Users:
      Count: 1
