
OrdererOrgs:
  - Name: Orderer
    Domain: rawcubes.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: org1.rawcubes.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.rawcubes.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.rawcubes.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org4
    Domain: org4.rawcubes.com
    Template:
      Count: 2
    Users:
      Count: 1
